version: '3.8'

services:
  admin:
    build:
      context: ./admin
    container_name: admin-dev
    ports:
      - "5174:5174"
    volumes:
      - ./admin:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    environment:
      - NODE_ENV=development

  user_guest:
    build:
      context: ./user_guest
    container_name: user-guest-dev
    ports:
      - "5173:5173"
    volumes:
      - ./user_guest:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    environment:
      - NODE_ENV=development