
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password}
      POSTGRES_DB: ${pg_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    image: backend:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONPATH: /app
      REDIS_HOST: ${REDIS_HOST}
      DB_URL: ${DB_URL}
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: